language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "node"

before_script:
  - npm install -g bower
  - bower install
#   - npm install -g karma
#   - npm install -g grunt
#   - npm install -g karma-jasmine
#   - npm install -g karma-phantomjs-launcher
#
# script: grunt karma
